import { IntelligenceEntry, OutreachEntry, CaseStatEntry, SectionMeta } from '../types';

export const SECTIONS_CONFIG: SectionMeta[] = [
  {
    id: 'D.IN.1',
    code: 'D.IN.1',
    name: 'Ideologi, Politik, Pertahanan & Keamanan',
    shortName: 'Ipolhankam',
    description: 'Pengawasan bidang ideologi, partai politik, pemilu/pilkada, ormas, dan stabilitas keamanan wilayah.',
    color: 'emerald',
    iconName: 'ShieldAlert',
    defaultKeterangan: ['Politik', 'Ideologi', 'Pertahanan', 'Keamanan Teritorial', 'Organisasi Masyarakat (Ormas)', 'Pilkada / Pemilu'],
  },
  {
    id: 'D.IN.3',
    code: 'D.IN.3',
    name: 'Sosial, Budaya & Kemasyarakatan',
    shortName: 'Sosbudkem',
    description: 'Pengawasan aliran kepercayaan masyarakat (PAKEM), isu SARA, adat istiadat, dan gesekan sosial.',
    color: 'sky',
    iconName: 'Users',
    defaultKeterangan: ['Pengawasan Aliran Kepercayaan (PAKEM)', 'Adat & Budaya', 'Isu Sosial & SARA', 'Pendidikan & Agama', 'Ketenagakerjaan'],
  },
  {
    id: 'D.IN.4',
    code: 'D.IN.4',
    name: 'Ekonomi & Keuangan',
    shortName: 'Ekokeu',
    description: 'Pemantauan stabilitas harga pangan, distribusi pupuk bersubsidi, mafia tanah, pajak daerah & moneter.',
    color: 'amber',
    iconName: 'TrendingUp',
    defaultKeterangan: ['Stabilitas Pangan & Inflasi', 'Pupuk Bersubsidi', 'Mafia Tanah', 'Moneter & Perbankan', 'Pendapatan Asli Daerah (PAD)'],
  },
  {
    id: 'D.IN.5',
    code: 'D.IN.5',
    name: 'Pengamanan Pembangunan Strategis',
    shortName: 'PPS',
    description: 'Pengawalan dan pengamanan proyek strategis nasional dan daerah dari potensi AGHT (Ancaman, Gangguan, Hambatan, Tantangan).',
    color: 'indigo',
    iconName: 'HardHat',
    defaultKeterangan: ['Proyek Strategis Daerah (PSD)', 'Infrastruktur Kesehatan', 'Pengairan & Irigasi Subak', 'Jalan & Jembatan', 'Fasilitas Publik'],
  },
  {
    id: 'D.IN.6',
    code: 'D.IN.6',
    name: 'Teknologi Informasi & Produksi Intelijen',
    shortName: 'TI & Prodintel',
    description: 'Patroli siber media sosial, penangkalan hoaks/disinformasi, dan produksi produk intelijen (LHI, LII, Lapinhar).',
    color: 'violet',
    iconName: 'Cpu',
    defaultKeterangan: ['Cyber Patrol', 'Produksi Produk Intelijen', 'Counter Disinformasi', 'Keamanan Siber', 'Intelijen Media'],
  },
  {
    id: 'D.IN.7',
    code: 'D.IN.7',
    name: 'Penerangan & Penyuluhan Hukum',
    shortName: 'Penkum & Luhkum',
    description: 'Kegiatan edukasi hukum masyarakat, Jaksa Masuk Sekolah (JMS), Jaksa Menyapa, dan pencegahan tindak pidana.',
    color: 'teal',
    iconName: 'BookOpen',
    defaultKeterangan: ['Jaksa Masuk Sekolah (JMS)', 'Jaksa Menyapa', 'Penyuluhan Hukum Dana Desa', 'Penerangan Hukum Instansi'],
  },
];

export const TABANAN_KECAMATAN = [
  'Tabanan',
  'Kediri',
  'Marga',
  'Baturiti',
  'Kerambitan',
  'Penebel',
  'Pupuan',
  'Selemadeg',
  'Selemadeg Barat',
  'Selemadeg Timur',
];

export const INITIAL_ENTRIES: IntelligenceEntry[] = [
  {
    id: 'din-101',
    no: 'REG-01/D.IN.1/TAB/2026',
    section: 'D.IN.1',
    sektor_symbol: 'PO',
    keterangan: 'Politik',
    narrative: 'Bahwa pada hari Selasa, tanggal 17 Februari 2026, Tim Intelijen Kejaksaan Negeri Tabanan telah melaksanakan pemantauan dan pengumpulan bahan keterangan terkait tahapan persiapan verifikasi administrasi pengurus partai politik tingkat Kabupaten Tabanan bertempat di Kantor KPUD Kabupaten Tabanan, Jl. Bypass Ir. Soekarno. Berdasarkan hasil koordinasi dengan Komisioner KPU, proses berjalan kondusif tanpa adanya potensi ancaman gangguan hambatan tantangan (AGHT), namun tetap dilakukan monitoring intensif menjelang agenda pleno terbuka.',
    date: '2026-02-17',
    reportDate: '2026-02-18',
    location: 'Kantor KPUD Tabanan, Jl. Bypass Ir. Soekarno',
    kecamatan: 'Tabanan',
    classification: 'TERBATAS',
    officerName: 'I Putu Arya, S.H. (Jaksa Fungsional Intelijen)',
    sourceConfidence: 'A1',
    status: 'SELESAI',
    createdAt: Date.now() - 86400000 * 4,
    updatedAt: Date.now() - 86400000 * 4,
  },
  {
    id: 'din-102',
    no: 'REG-02/D.IN.1/TAB/2026',
    section: 'D.IN.1',
    sektor_symbol: 'KT',
    keterangan: 'Keamanan Teritorial',
    narrative: 'Bahwa pada hari Kamis, tanggal 12 Februari 2026 sekitar pukul 10.00 WITA, diperoleh informasi terkait adanya ketegangan batas tanah ulayat/adat di wilayah perbatasan Desa Candikuning dengan Desa Batunya Kecamatan Baturiti. Tim Intelijen telah melakukan deteksi dini berkoordinasi dengan Majelis Desa Adat (MDA) Kecamatan Baturiti dan Kapolsek Baturiti guna meredam eskalasi konflik secara musyawarah kekeluargaan demi menjaga kondusivitas keamanan wilayah pariwisata Bedugul.',
    date: '2026-02-12',
    reportDate: '2026-02-13',
    location: 'Batas Ulayat Desa Candikuning - Batunya',
    kecamatan: 'Baturiti',
    classification: 'RAHASIA',
    officerName: 'Gede Agus Wirawan, S.H. (Staf Intelijen)',
    sourceConfidence: 'B1',
    status: 'DALAM_PEMANTAUAN',
    createdAt: Date.now() - 86400000 * 9,
    updatedAt: Date.now() - 86400000 * 9,
  },
  {
    id: 'din-103',
    no: 'REG-03/D.IN.1/TAB/2026',
    section: 'D.IN.1',
    sektor_symbol: 'OR',
    keterangan: 'Organisasi Masyarakat (Ormas)',
    narrative: 'Bahwa pada hari Jumat, tanggal 06 Februari 2026, telah dilaksanakan kegiatan koordinasi dan pendataan ulang terhadap ormas dan LSM yang terdaftar di Bakesbangpol Kabupaten Tabanan. Dari total 42 ormas terdaftar, sebanyak 38 ormas berstatus aktif berkegiatan sosial kemasyarakatan dan tertib administrasi, serta tidak ditemukan indikasi terafiliasi dengan paham radikalisme.',
    date: '2026-02-06',
    reportDate: '2026-02-07',
    location: 'Kantor Bakesbangpol Tabanan',
    kecamatan: 'Tabanan',
    classification: 'BIASA',
    officerName: 'Kadek Mahendra, S.H. (Kasi Intelijen)',
    sourceConfidence: 'A1',
    status: 'SELESAI',
    createdAt: Date.now() - 86400000 * 15,
    updatedAt: Date.now() - 86400000 * 15,
  },
  {
    id: 'din-301',
    no: 'REG-01/D.IN.3/TAB/2026',
    section: 'D.IN.3',
    sektor_symbol: 'PK',
    keterangan: 'Pengawasan Aliran Kepercayaan (PAKEM)',
    narrative: 'Bahwa pada hari Rabu, tanggal 18 Februari 2026, Tim Koordinasi Pengawasan Aliran Kepercayaan dan Keagamaan dalam Masyarakat (PAKEM) Kejari Tabanan menggelar rapat koordinasi bersama Kemenag, FKUB, MDA, dan Polres Tabanan. Pembahasan difokuskan pada pemantauan kegiatan kelompok spiritual di kawasan Penebel agar tetap selaras dengan ketentuan hukum dan tidak menimbulkan keresahan warga sekitar.',
    date: '2026-02-18',
    reportDate: '2026-02-19',
    location: 'Aula Kejaksaan Negeri Tabanan',
    kecamatan: 'Tabanan',
    classification: 'TERBATAS',
    officerName: 'Kadek Mahendra, S.H. (Kasi Intelijen)',
    sourceConfidence: 'A1',
    status: 'SELESAI',
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now() - 86400000 * 3,
  },
  {
    id: 'din-401',
    no: 'REG-01/D.IN.4/TAB/2026',
    section: 'D.IN.4',
    sektor_symbol: 'SP',
    keterangan: 'Stabilitas Pangan & Inflasi',
    narrative: 'Bahwa pada hari Senin, tanggal 16 Februari 2026, Tim Intelijen bersama Satgas Pangan Kabupaten Tabanan melakukan operasi pasar monitoring harga dan ketersediaan komoditas bahan pokok (Beras Medium, Cabai Rawit, Minyak Goreng) di Pasar Tradisional Dauh Pala Tabanan dan Pasar Kediri. Stok beras terpantau aman dan harga relatif stabil dengan pasokan lancar dari sentra penggilingan padi Selemadeg.',
    date: '2026-02-16',
    reportDate: '2026-02-16',
    location: 'Pasar Dauh Pala & Pasar Kediri',
    kecamatan: 'Kediri',
    classification: 'BIASA',
    officerName: 'I Wayan Sudiarta, S.H.',
    sourceConfidence: 'A1',
    status: 'SELESAI',
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now() - 86400000 * 5,
  },
  {
    id: 'din-501',
    no: 'REG-01/D.IN.5/TAB/2026',
    section: 'D.IN.5',
    sektor_symbol: 'PS',
    keterangan: 'Proyek Strategis Daerah (PSD)',
    narrative: 'Bahwa pada hari Rabu, tanggal 11 Februari 2026, Tim Pengamanan Pembangunan Strategis (PPS) Kejaksaan Negeri Tabanan melakukan peninjauan lapangan berkala terhadap Proyek Pembangunan Gedung Rawat Inap Terpadu RSUD Nyitdah Tabanan (Tahap II). Progres fisik telah mencapai 68,4% (deviasi positif +2,1%), dan tidak ditemukan adanya indikasi penyimpangan maupun hambatan teknis yang signifikan.',
    date: '2026-02-11',
    reportDate: '2026-02-12',
    location: 'Kompleks RSUD Nyitdah, Desa Nyitdah',
    kecamatan: 'Kediri',
    classification: 'TERBATAS',
    officerName: 'Tim PPS Kejari Tabanan',
    sourceConfidence: 'A1',
    status: 'DALAM_PEMANTAUAN',
    createdAt: Date.now() - 86400000 * 10,
    updatedAt: Date.now() - 86400000 * 10,
  },
  {
    id: 'din-601',
    no: 'REG-01/D.IN.6/TAB/2026',
    section: 'D.IN.6',
    sektor_symbol: 'CP',
    keterangan: 'Cyber Patrol',
    narrative: 'Bahwa pada hari Minggu, tanggal 15 Februari 2026, Tim Cyber Intelijen Kejari Tabanan melakukan patroli siber di platform media sosial (Facebook, Instagram, TikTok) dan menemukan 2 akun anonim yang menyebarkan narasi provokatif bermuatan SARA terkait pemilihan bendesa adat. Tim telah menyusun Nota Pendapat Intelijen dan berkoordinasi dengan Tim Siber Polda Bali serta Diskominfos Tabanan untuk take-down klarifikasi.',
    date: '2026-02-15',
    reportDate: '2026-02-15',
    location: 'Posko Cyber Intelijen Kejari Tabanan',
    kecamatan: 'Tabanan',
    classification: 'RAHASIA',
    officerName: 'I Putu Arya, S.H.',
    sourceConfidence: 'A2',
    status: 'TINDAK_LANJUT',
    createdAt: Date.now() - 86400000 * 6,
    updatedAt: Date.now() - 86400000 * 6,
  },
];

export const TABANAN_COORDINATES: Record<string, { lat: number; lng: number }> = {
  Tabanan: { lat: -8.5385, lng: 115.1232 },
  Kediri: { lat: -8.5721, lng: 115.1438 },
  Baturiti: { lat: -8.3245, lng: 115.1834 },
  Marga: { lat: -8.4891, lng: 115.1764 },
  Kerambitan: { lat: -8.5441, lng: 115.0862 },
  Penebel: { lat: -8.4357, lng: 115.1384 },
  Pupuan: { lat: -8.3562, lng: 115.0215 },
  Selemadeg: { lat: -8.4983, lng: 115.0451 },
  'Selemadeg Barat': { lat: -8.4552, lng: 114.9812 },
  'Selemadeg Timur': { lat: -8.5451, lng: 115.0612 },
};

export const INITIAL_OUTREACH: OutreachEntry[] = [
  {
    id: 'outreach-101',
    no: 'JMS/01/TRI-I/2026',
    triwulan: 1,
    jenis_kegiatan: 'Jaksa Masuk Sekolah (JMS)',
    tema_kegiatan: 'Kenali Hukum, Jauhi Hukuman: Pencegahan Bullying & Bahaya Narkoba di Kalangan Pelajar',
    waktu: '2026-01-22',
    tempat: 'Aula SMAN 1 Tabanan',
    kecamatan: 'Tabanan',
    jumlah_peserta: 185,
    target_peserta: 150,
    narasumber: 'I Putu Arya, S.H. & Tim Penerangan Hukum',
    materi_pokok: 'UU ITE, UU Perlindungan Anak, dan Bahaya Narkotika',
    photoUrl: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?w=800&q=80',
    photoCaption: 'Penyampaian materi hukum dan sesi tanya jawab bersama 185 siswa SMAN 1 Tabanan',
    latitude: -8.5372,
    longitude: 115.1245,
    status: 'TERLAKSANA',
    createdAt: Date.now() - 86400000 * 30,
    updatedAt: Date.now() - 86400000 * 30,
  },
  {
    id: 'outreach-102',
    no: 'PENKUM/01/TRI-I/2026',
    triwulan: 1,
    jenis_kegiatan: 'Penyuluhan Hukum',
    tema_kegiatan: 'Pengawalan Akuntabilitas Pengelolaan Dana Desa & Pencegahan Tindak Pidana Korupsi bagi Perbekel',
    waktu: '2026-02-05',
    tempat: 'Gedung Pertemuan Kantor Camat Baturiti',
    kecamatan: 'Baturiti',
    jumlah_peserta: 94,
    target_peserta: 80,
    narasumber: 'Kasi Intelijen & Jaksa Penyidik Tipikor',
    materi_pokok: 'Mitigasi Risiko Hukum Pengadaan Barang dan Jasa di Desa',
    photoUrl: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=800&q=80',
    photoCaption: 'Sosialisasi mitigasi risiko hukum bersama 12 Perbekel & Bendahara Desa se-Kecamatan Baturiti',
    latitude: -8.3245,
    longitude: 115.1834,
    status: 'TERLAKSANA',
    createdAt: Date.now() - 86400000 * 16,
    updatedAt: Date.now() - 86400000 * 16,
  },
  {
    id: 'outreach-103',
    no: 'JMEN/01/TRI-I/2026',
    triwulan: 1,
    jenis_kegiatan: 'Jaksa Menyapa',
    tema_kegiatan: 'Dialog Interaktif: Peran Intelijen Kejaksaan dalam Menjaga Ketenteraman Masyarakat',
    waktu: '2026-02-19',
    tempat: 'Studio RSPD 97.9 FM Tabanan',
    kecamatan: 'Tabanan',
    jumlah_peserta: 320,
    target_peserta: 200,
    narasumber: 'Kadek Mahendra, S.H. (Kasi Intelijen Kejari Tabanan)',
    materi_pokok: 'Pemberitahuan Saluran Pengaduan Posko Pemilu dan Dumas Intelijen',
    photoUrl: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=800&q=80',
    photoCaption: 'Siaran langsung dialog interaktif program Jaksa Menyapa di Studio Radio Pemkab Tabanan FM',
    latitude: -8.5412,
    longitude: 115.1189,
    status: 'TERLAKSANA',
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now() - 86400000 * 2,
  },
  {
    id: 'outreach-104',
    no: 'JMS/02/TRI-I/2026',
    triwulan: 1,
    jenis_kegiatan: 'Jaksa Masuk Sekolah (JMS)',
    tema_kegiatan: 'Generasi Cerdas Bebas Judi Online & Tawuran Remaja',
    waktu: '2026-02-26',
    tempat: 'Auditorium SMPN 1 Marga',
    kecamatan: 'Marga',
    jumlah_peserta: 140,
    target_peserta: 120,
    narasumber: 'Tim Penkum Seksi Intelijen Kejari Tabanan',
    materi_pokok: 'Edukasi Dampak Buruk Judol dan Perlindungan Cyber Law',
    photoUrl: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&q=80',
    photoCaption: 'Pemberian plakat edukasi hukum kepada Kepala Sekolah SMPN 1 Marga',
    latitude: -8.4891,
    longitude: 115.1764,
    status: 'TERLAKSANA',
    createdAt: Date.now() - 86400000 * 1,
    updatedAt: Date.now() - 86400000 * 1,
  },
  {
    id: 'outreach-105',
    no: 'PENKUM/02/TRI-I/2026',
    triwulan: 1,
    jenis_kegiatan: 'Penerangan Hukum',
    tema_kegiatan: 'Tata Kelola BUMDes & Perlindungan Aset Desa Adat',
    waktu: '2026-03-04',
    tempat: 'Balai Banjar Desa Kerambitan',
    kecamatan: 'Kerambitan',
    jumlah_peserta: 75,
    target_peserta: 70,
    narasumber: 'Jaksa Fungsional Intelijen',
    materi_pokok: 'Penyusunan Peraturan Desa dan Pencegahan Maladministrasi Keuangan',
    photoUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&q=80',
    photoCaption: 'Forum diskusi Penerangan Hukum tata kelola BUMDes di Kerambitan',
    latitude: -8.5441,
    longitude: 115.0862,
    status: 'TERLAKSANA',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'outreach-201',
    no: 'JMS/03/TRI-II/2026',
    triwulan: 2,
    jenis_kegiatan: 'Jaksa Masuk Sekolah (JMS)',
    tema_kegiatan: 'Literasi Digital & Bijak Bermedia Sosial bagi Remaja',
    waktu: '2026-04-15',
    tempat: 'SMPN 1 Kediri',
    kecamatan: 'Kediri',
    jumlah_peserta: 0,
    target_peserta: 160,
    narasumber: 'Tim Penkum Kejari Tabanan',
    materi_pokok: 'Pencegahan Judi Online & Pornografi Anak',
    photoUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&q=80',
    photoCaption: 'Rencana lokasi pelaksanaan JMS di Gedung Serbaguna SMPN 1 Kediri',
    latitude: -8.5721,
    longitude: 115.1438,
    status: 'TERJADWAL',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'outreach-202',
    no: 'PENKUM/03/TRI-II/2026',
    triwulan: 2,
    jenis_kegiatan: 'Penyuluhan Hukum',
    tema_kegiatan: 'Perlindungan Hukum Petani & Distribusi Pupuk Subsidi',
    waktu: '2026-05-12',
    tempat: 'Balai Pertemuan Subak Jatiluwih, Penebel',
    kecamatan: 'Penebel',
    jumlah_peserta: 0,
    target_peserta: 100,
    narasumber: 'Tim Intelijen & Dinas Pertanian Tabanan',
    materi_pokok: 'Pengawasan Pupuk Subsidi & Pencegahan Penyelewengan',
    latitude: -8.4357,
    longitude: 115.1384,
    status: 'TERJADWAL',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];

export const INITIAL_CASE_STATS: CaseStatEntry[] = [
  // 2026
  {
    id: 'case-stats:Korupsi:2026',
    category: 'Korupsi',
    year: 2026,
    stages: {
      lid_spdp: 4,
      dik_kejaksaan: 2,
      dik_kepolisian: 1,
      tut: 2,
    },
    notes: 'Perkara dugaan penyelewengan dana LPD & APBDes',
    updatedAt: Date.now(),
  },
  {
    id: 'case-stats:Narkotika:2026',
    category: 'Narkotika',
    year: 2026,
    stages: {
      lid_spdp: 18,
      dik_kejaksaan: 0,
      dik_kepolisian: 16,
      tut: 14,
    },
    notes: 'Didominasi peredaran sabu & ganja sintetis lintas jalur Gilimanuk-Denpasar',
    updatedAt: Date.now(),
  },
  {
    id: 'case-stats:Terorisme:2026',
    category: 'Terorisme',
    year: 2026,
    stages: {
      lid_spdp: 0,
      dik_kejaksaan: 0,
      dik_kepolisian: 0,
      tut: 0,
    },
    notes: 'Nihil perkara aktif (kondusif)',
    updatedAt: Date.now(),
  },
  {
    id: 'case-stats:Perkara Menarik Perhatian Masyarakat:2026',
    category: 'Perkara Menarik Perhatian Masyarakat',
    year: 2026,
    stages: {
      lid_spdp: 6,
      dik_kejaksaan: 1,
      dik_kepolisian: 5,
      tut: 4,
    },
    notes: 'Kasus tindak pidana pencurian pratima & sengketa tanah waris adat',
    updatedAt: Date.now(),
  },

  // 2025
  {
    id: 'case-stats:Korupsi:2025',
    category: 'Korupsi',
    year: 2025,
    stages: {
      lid_spdp: 7,
      dik_kejaksaan: 5,
      dik_kepolisian: 2,
      tut: 5,
    },
    notes: 'Putusan inkracht 4 perkara',
    updatedAt: Date.now() - 86400000 * 90,
  },
  {
    id: 'case-stats:Narkotika:2025',
    category: 'Narkotika',
    year: 2025,
    stages: {
      lid_spdp: 46,
      dik_kejaksaan: 0,
      dik_kepolisian: 42,
      tut: 39,
    },
    notes: 'Telah dilakukan eksekusi barang bukti pemusnahan',
    updatedAt: Date.now() - 86400000 * 90,
  },
  {
    id: 'case-stats:Terorisme:2025',
    category: 'Terorisme',
    year: 2025,
    stages: {
      lid_spdp: 0,
      dik_kejaksaan: 0,
      dik_kepolisian: 0,
      tut: 0,
    },
    notes: 'Nihil',
    updatedAt: Date.now() - 86400000 * 90,
  },
  {
    id: 'case-stats:Perkara Menarik Perhatian Masyarakat:2025',
    category: 'Perkara Menarik Perhatian Masyarakat',
    year: 2025,
    stages: {
      lid_spdp: 14,
      dik_kejaksaan: 3,
      dik_kepolisian: 11,
      tut: 10,
    },
    notes: 'Kasus pelecehan lingkungan & penipuan investasi bodong',
    updatedAt: Date.now() - 86400000 * 90,
  },

  // 2024
  {
    id: 'case-stats:Korupsi:2024',
    category: 'Korupsi',
    year: 2024,
    stages: {
      lid_spdp: 6,
      dik_kejaksaan: 4,
      dik_kepolisian: 2,
      tut: 4,
    },
    notes: 'Penyelamatan keuangan negara Rp 1,4 Miliar',
    updatedAt: Date.now() - 86400000 * 400,
  },
  {
    id: 'case-stats:Narkotika:2024',
    category: 'Narkotika',
    year: 2024,
    stages: {
      lid_spdp: 38,
      dik_kejaksaan: 0,
      dik_kepolisian: 38,
      tut: 35,
    },
    notes: 'Restorative justice rehabilitasi 3 perkara',
    updatedAt: Date.now() - 86400000 * 400,
  },
  {
    id: 'case-stats:Terorisme:2024',
    category: 'Terorisme',
    year: 2024,
    stages: {
      lid_spdp: 0,
      dik_kejaksaan: 0,
      dik_kepolisian: 0,
      tut: 0,
    },
    notes: 'Nihil',
    updatedAt: Date.now() - 86400000 * 400,
  },
  {
    id: 'case-stats:Perkara Menarik Perhatian Masyarakat:2024',
    category: 'Perkara Menarik Perhatian Masyarakat',
    year: 2024,
    stages: {
      lid_spdp: 12,
      dik_kejaksaan: 2,
      dik_kepolisian: 10,
      tut: 9,
    },
    notes: 'Kasus tindak pidana pengeroyokan di Kerambitan',
    updatedAt: Date.now() - 86400000 * 400,
  },
];
